apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
spec:
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: samson2ky/dotnetapp:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: Mongo__Username
            valueFrom:
              secretKeyRef:
                name: dotnetapp-secrets
                key: username
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                name: dotnetapp-secrets
                key: password
          - name: Mongo__Host
            value: dotnetdb-service
        ports:
        - containerPort: 80
          name: dotnetapp-port
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-service
spec:
  type: LoadBalancer
  selector:
    app: dotnetapp
  ports:
  - port: 80
    targetPort: dotnetapp-port

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dotnetdb
spec:
  selector:
    matchLabels:
      app: dotnetdb
  serviceName: dotnetdb-service
  template:
    metadata:
      labels:
        app: dotnetdb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: dotnetdb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dotnetdb-secret
              key: password
        ports:
        - containerPort: 27017
          name: databaseport
        volumeMounts:
        - name: dbvolume
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: dbvolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: dotnetdb-service
spec:
  clusterIP: None
  selector:
    app: dotnetdb
  ports:
  - port: 27017
    targetPort: databaseport
